### ISSUE TITLE
README.md: Import JSON: Example does not provide newline after last row

### ISSUE THREAD

**Issue by nakami** [lukasmartinelli/pgfutter#10]
In the given example `friends.json` in the `README.md`, three objects (or rows) are set up.
However, the last object will only be handled if it is followed by a new line which isn't particulary clear in the `README.md`.

**Comment by lukasmartinelli** [comment]
Thx. Added the newline.
What was the error message or what did pgfutter complain that it was unclear?

**Comment by nakami** [comment]
pgfutter just ignored the last line and imported merely the first two lines. 
It also told me that it only imported those two, so it's not a big deal.

Thank you.
