### ISSUE TITLE
JSONB instead of JSON

### ISSUE THREAD

**Issue by mickdelaney** [lukasmartinelli/pgfutter#17]
Hi,
Would it be possible/make sense to allow JSONB instead of JSON as the data column type ?
Currently I end up changing the data column to JSONB after its imported which takes time. 

Thanks for the a great project btw.

Regards

**Comment by buildbreakdo** [comment]
Can you close this? Quickly scanned this the other day and somehow thought it hadn't been implemented yet and it has. Thanks so much for this lib, has significantly improved my work flow! Awesome work! 👍

**Comment by buildbreakdo** [comment]
Used the Linux wget link: wget -O pgfutter https://github.com/lukasmartinelli/pgfutter/releases/download/v1.0/pgfutter_linux_amd64

And realised this version dow not have jsonb support. Is it possible to update the download links to get latest? Looks like you can here: https://help.github.com/articles/linking-to-releases/ with 

> Right click on Latest Release and copy the URL to share it. The suffix of this URL is always /releases/latest.

But is that only if a release has been tagged (would be nice from a maintenance perspective if this was not true, so the urls would not have to be updated all the time)? 

Just trying to get the latest version with all the goodies :)

**Comment by buildbreakdo** [comment]
Using `go get` worked to get the latest. Strange that both are listed as version 1.0 when they have different feature sets.  Looked at semantic versioning that is popular with the node crowd? http://semver.org/

**Comment by buildbreakdo** [comment]
Would recommend following semver as close as possible, it is well understood and documented. The three biggest Go projects that I am aware of use semver as well CoreOS, Kubernetes, and Docker.

Yeah the bump to 1.0.0 makes sense when you have a stable API. Think their summary is on point:

> Given a version number MAJOR.MINOR.PATCH, increment the:

> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
