### ISSUE TITLE
Windows/DOS end of line causes pgfutter to treat all data as one row

### ISSUE THREAD

**Issue by manueltimita** [lukasmartinelli/pgfutter#19]
Great software and very helpful! Also withstands the [csv-spectrum](https://github.com/maxogden/csv-spectrum) tests. Thumbs up!

I just identified an issue with the line endings. If the CSV file has Windows EOLs (and, for that matter, I would think legacy Mac ones too), then pgfutter treats it as containing one row only - basically the header. Thus it throws the weirdest of errors with some otherwise valid (in the Apple/Microsoft worlds) files.

To test that for yourself, you could use one of these files: [file1](http://samplecsvs.s3.amazonaws.com/TechCrunchcontinentalUSA.csv), [file2](http://samplecsvs.s3.amazonaws.com/SalesJan2009.csv).

For those users having the same issue, a temporary fix would be to [programmatically] pass the file through a Bash script which replaces the EOLs. Good [cross platform instructions here](https://developer.apple.com/library/mac/documentation/OpenSource/Conceptual/ShellScripting/PortingScriptstoMacOSX/PortingScriptstoMacOSX.html).

**Comment by manueltimita** [comment]
I realised that a quick example could be helpful:

What the file looks like on Win:
```csv
permalink,company,numEmps,category,city,state,fundedDate,raisedAmt,raisedCurrency,round
lifelock,LifeLock,,web,Tempe,AZ,1-May-07,6850000,USD,b
lifelock,LifeLock,,web,Tempe,AZ,1-Oct-06,6000000,USD,a
```

What vim on Linux sees:
```
permalink,company,numEmps,category,city,state,fundedDate,raisedAmt,raisedCurrency,round^Mlifelock,LifeLock,,web,Tempe,AZ,1-May-07,6850000,USD,b^Mlifelock,LifeLock,,web,Tempe,AZ,1-Oct-06,6000000,USD,a
```

Notice the **^M** character in the second example.

**Comment by acook** [comment]
Both of those files are `\r` line endings only, which the Go developers have flatly [refused to support](https://github.com/golang/go/issues/7802).

There is [a Go package](https://godoc.org/github.com/ctessum/macreader) which converts `\r` line endings into standard `\n` line endings, which `pgfutter` could use to convert files after a short detection routine. 

**`\r\n` files load just fine.** You can test it using [this file](https://www.microsoft.com/en-us/download/details.aspx?id=45485) from Microsoft.

**Comment by lukasmartinelli** [comment]
I know support this by using a different csv package #51.
Use the `--excel` arg for csv mode to support this use case in v1.2
