### ISSUE TITLE
Where does the single JSON object get stored in memory?

### ISSUE THREAD

**Issue by XYTYX** [lukasmartinelli/pgfutter#21]
Hi Lukas,
According to your docs...

> Instead of using JSON lines you can also import a single JSON object into the database. This will load the JSON document into memory first.
> I'm unsure of what this means, I've executed the command with no errors, but where in memory is my uploaded(?) JSON object?

Thanks in advance.

**Comment by lukasmartinelli** [comment]
> This will load the JSON document into memory first.

What I meant by this is that if you have a very large JSON object (2GB) this will also require 2GB memory to load the object into the buffer. But this has nothing to do with the database.

I recommend to use json lines importing a single JSON object was a use case in this issue https://github.com/lukasmartinelli/pgfutter/issues/9

But if you use the normal json lines an have `n` records you don't need O(n) space as each record is loaded into memory and decoded as you go.

**Comment by lukasmartinelli** [comment]
Single JSON mode is deprecated due to lack of use and instability #47
