### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by timiyay** [lukasmartinelli/pgfutter#23]
This is a really useful tool for getting unwieldy CSVs into Postgres for quick analysis.

Have you considered creating a Homebrew formula for it, for easy installation on OSX?

**Comment by lukasmartinelli** [comment]
> Have you considered creating a Homebrew formula for it, for easy installation on OSX?

Considered it but I think I cannot let homebrew download binaries (so you require the Go ecosystem on your machine to install pgfutter).
That's why I haven't done it yet - I think downloading a binary is perhaps easier to set up.

But would be very happy if you contribute a formula!!

**Comment by joallard** [comment]
Used pgfutter this morning and it was a real life-saver, so I created my first homebrew formula: https://gist.github.com/joallard/11a97b2ee3eed44f1a93690fecdfe92a, but it's still pretty drafty. We can probably incorporate this into this repo or homebrew/core at some point.

**Comment by lukasmartinelli** [comment]
> Used pgfutter this morning and it was a real life-saver, so I created my first homebrew formula: https://gist.github.com/joallard/11a97b2ee3eed44f1a93690fecdfe92a, but it's still pretty drafty. We can probably incorporate this into this repo or homebrew/core at some point.

Thanks for the draft @joallard! ❤️ 
Makes sense to have it as Go program it can be in homebrew!
Would be very thankful if you push it to homebrew. They have pretty good documentation how to do it.

You used pgfutter for CSV or JSON imports?

**Comment by joallard** [comment]
I think the brew repo has some more criteria to have it in, I'm waiting for some people who test the script, and then we can probably get their input.

I used it to import a CSV with the schema, it was pretty easy.

**Comment by timiyay** [comment]
I haven't been using this tool lately, less DB tasks in my contemporary role. Closing this issue for the time being, as it's stale.
