### ISSUE TITLE
null values in csv are imported as empty strings

### ISSUE THREAD

**Issue by drewnichols** [lukasmartinelli/pgfutter#30]
I have a csv file which contains a number of null values in string columns. For example:

```
col_a, col_b,col_c
"val a",,"val c"
"val b",,"val c"
```

Once imported, the empty values are cast into empty strings. Is there a way to get it to import them as null?

**Comment by lukasmartinelli** [comment]
Everything is a string deliberately. I recommend write SQL to clean up the import data and move it from the `import` schema to `public`. 
Like in example here: https://github.com/lukasmartinelli/pgfutter#import-csv

**Comment by lukasmartinelli** [comment]
Or perhaps if you create the table beforehand with the right types it will automatically cast? not sure

**Comment by drewnichols** [comment]
ok it's by design...
